# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAS_SAMPLE_014' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LAS_SAMPLE_014
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'lottie-ios' 

  target 'LAS_SAMPLE_014Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LAS_SAMPLE_014UITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
